#!/bin/sh
#
# Author mod : Stefano Viola (aka) Esteban Sannin
#

VERSION=0.2-bblog

EDITOR=vi
INDEX=index.html
FORMAT=html
SEC=`date +%s`
PUBLISHED=[`date "+%m %b %Y - %R"`]
DIR=data
FOOTERTXT=user@bblog

TITLE_SITE=user@bblog~$
OUTPUT_TOP=post_top
MESSAGE=message_post
OUTPUT_BOT=post_bottom
POST_PUBLISHED=published
CONFIG=bblog.conf
DESTINATION_DIR=
THEME_DIR=themes/

THEME=default

### Remote Upload Parm ###
FTP_HOST=esteban.homelinux.org
FTP_LOGIN=esteban
FTP_REMOTE_DIR=/var/mounts/sda1/var/www/bblog

# funzione che genera il link per la pagina principale
 update_index(){
         echo "<!-- ;${SEC}; postblog-->${PUBLISHED}:<a href=\"${DIR}/${SEC}.$TITLE.${FORMAT}\"> ${TITLE}</a>" >> ${INDEX}
}

# pagina del post blog

post_top(){
        echo "<!-- <?xml version=\"1.0\" encoding=\"UTF-8\" ?> --><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><link rel=\"stylesheet\" href=\"$THEME_PAGE\" type=\"text/css\">"  >> ${FINAL}
        echo "<head><title>${TITLE} - ${DATE}</title></head>"  >> ${FINAL}
        echo "<body>"  >> ${FINAL}
        echo "<meta http-equiv=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">" >> ${FINAL}
        echo "<div id=\"footer\"><pre><font color=red>  BBLOG</font> version by <font color=yellow><a href=\"http://esteban.homelinux.org\">EstebanSannin</a></font></pre></div>" >> ${FINAL}
        echo "<div id=\"header\"><pre><h2>$TITLE_SITE</h2>" >> ${FINAL}
       # echo "<td class=\"headitem\">[<a href=\"../${INDEX}\">home</a>]</td>" >> ${FINAL}
       # echo "<td class=\"headitem\">[<a href=\"../tutorial/index.html\">tutorial</a>]</td></tr></table></div>" >> ${FINAL}
        echo "<div id=\"content\"><pre>" >> ${FINAL}
        echo "<a href=\"../${INDEX}\">[index]</a><a href=\"../\">[main]</a>" >> ${FINAL}
        echo           >> ${FINAL}
}

 post_bottom(){
         echo          >> ${FINAL}
         echo --       >> ${FINAL}
         echo ${FOOTERTXT} >> ${FINAL}
         echo "</pre>" >>  ${FINAL}
         echo "</body>" >>  ${FINAL}
         echo "</html>" >>  ${FINAL}
} 

# fine creazione pagina post

message_post(){
        cat temp.$FORMAT >> ${FINAL}
        rm temp.*
}

 format_main(){
         mkdir -p ${DIR} || echo ${DIR} exists...

         FINAL=$DIR/$SEC.$TITLE.$FORMAT
         ${OUTPUT_TOP} 
         ${MESSAGE}
         ${OUTPUT_BOT} 
}


# genera la home se non esiste
 home(){ 
         #mkdir -p ${DIR} || echo ${DIR} exists...
         if [ ! -e ${INDEX} ]; then
                 echo
                 echo "...creating ${INDEX}"
                 echo "<!-- ;10000000000000000000000000; open pre tag --><!-- <?xml version=\"1.0\" encoding=\"UTF-8\" ?> --><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><link rel=\"stylesheet\" href=\"$THEME_CSS\" type=\"text/css\"><head><title>$TITLE_SITE</title></head><body>" >> ${INDEX}
                 echo "<!-- ;1000000000000000000000000; utf8 meta tag  --><meta http-equiv=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">" >> ${INDEX}
                 echo "<!-- ;100000000000000000000000; fixed content --><div id=\"footer\"><pre><font color=red>  BBLOG</font> version by <font color=yellow><a href=\"http://esteban.homelinux.org\">EstebanSannin</a></font></pre></div>" >> ${INDEX}
                 echo "<!-- ;10000000000000000000000;  fixed content --><div id=\"header\"><pre><h2>$TITLE_SITE<blink>_</blink></h2><table border=\"0\"><tr>" >> ${INDEX}
                 echo "<!-- ;1000000000000000000000;   fixed content --><td class=\"headitem\">[<a href=\"../index.html\">return</a>]</td></tr></table></div>" >> ${INDEX}
                 echo "<!-- ;100000000000000000000;   fixed content --><div id=\"content\"><pre>" >> ${INDEX}
                 echo "<!-- ;10000000000000000000;   fixed content --><h3>LIST POST:</h3>" >> ${INDEX}
                 echo "<!-- ;3; fixed content -->" >> ${INDEX}
                 echo "<!-- ;2; fixed content -->" >> ${INDEX}
                 echo "<!-- ;0; closing pre tag --></pre></body></html>" >> ${INDEX}
                 echo
         fi
}

sort_index(){
         sort -t';' +0f -0 +1nr ${INDEX} > .${INDEX}.$$.sorted
         mv .${INDEX}.$$.sorted ${INDEX} # "rebuild ${INDEX}
}

get_post_title(){
        echo 
        echo -n "Insert Post Title: "
        read title
        TITLE=$title
}
read_config(){
        
        if [ -e $CONFIG  ]; then
                . ./$CONFIG
                echo -n "\n\n\tLoaded configuration file: $CONFIG\n\n"
        else
                echo -n "\n\n\tConfiguration file not loaded!\n\n"
        fi
}
control_destination_dir(){

	 cp $INDEX $DESTINATION_DIR
	 cp -r $THEME_DIR $DESTINATION_DIR
	 cp -r $DIR $DESTINATION_DIR
	 cp $CONFIG $DESTINATION_DIR
	 #echo "Contenuto spostato in: $DESTINATION_DIR"

}
move(){
	if [ -e $DESTINATION_DIR  ]; then
		#echo "il file esiste"
		control_destination_dir
		echo "Content moved to: $DESTINATION_DIR"
		echo
	else
		echo "Directory not exist. Do you want create one? (y/n)"
		read chose
		if [ $chose = "y" ]; then
			mkdir $DESTINATION_DIR
			control_destination_dir
		else if [ $chose = n  ]; then
			echo "Content not moved!"
		else
			echo "Error input!"
		fi
		fi
	fi
}

log_post(){
	
	cat index.html | grep post | cut -f2 -d\" > temp_post
}

list_post_published(){
	log_post
	echo -n "\n\n\tList of number Post:\n\n"
	cat -b temp_post
	echo -n "\n\n"
}

modify_post(){
	log_post
	list_post_published
	echo -n "Insert the number of posts you want to change: "
	read number
	number_post=`wc -l temp_post | awk {'print $1'}`
	echo "number: $number"
	if [ ! -z "$number" ]; then
		if [ "$number" -gt "$number_post" ]; then
			echo
			echo "The number of posts you entered is invalid!"
			list_post_published
		else
			$EDITOR `sed -n ${number}p temp_post`
		fi
	else
		echo "No number entered!"
		echo
	fi
}

upload(){
	stty -echo
	echo "Insert FTP password:"
	read passwd
	stty echo
	FTP_PASSWORD=$passwd


ncftp <<EOF
open -u $FTP_LOGIN -p $FTP_PASSWORD $FTP_HOST
set auto-resume yes
cd /var/mounts/sda1/var/www/bblog
put index.html
put -R data
mkdir themes
cd themes
put -R themes/*
bye
EOF


}

version(){
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""

}
usage(){
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""
	echo -n ""

}

###################################### *** MAIN *** ########################################

read_config  # Importa i parametri da bblog.conf

######**  Setting Theme  **######

STYLE=style.css
THEME_PAGE=../themes/$THEME/page/$STYLE
THEME_CSS=themes/$THEME/$STYLE

######**End Setting Theme**######

echo -n "\n\n\tInformation Setting:\n\n"
echo "THEME used: $THEME"
echo "TITLE_SITE: $TITLE_SITE"
echo "PAGE NAME:  $INDEX"


case "$1" in

      --post)
              get_post_title
              $EDITOR temp.$FORMAT
              format_main
              home
              update_index
              sort_index
              echo "New Post Added to $INDEX!"
              echo
	      log_post
              #echo $TITLE >> $POST_PUBLISHED
	
              ;;
      --list) echo -n "\n\n\tPost LIST:\n\n"
              ls -1 -r $DIR
              echo
              ;;

    --config)
              echo "configure"
              ;;
      --edit)
              echo "edit"
	      modify_post
              ;;
      --info)
              echo "Info"
              ;;
    --upload) 
	      echo "Upload"
	      upload
              ;;
      --move)
	      echo -n "Insert Dir: "
	      read dir
	      DESTINATION_DIR=$dir
	      move
	      ;;


           *) echo error
              ;;
esac




########## END ######################
